// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(GestionDbContext))]
    [Migration("20240504213649_facturacion")]
    partial class facturacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Authorization.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.RolesUser", b =>
                {
                    b.Property<int>("RolesUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesUserId"));

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RolesUserId");

                    b.HasIndex("RolId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RolesUser");

                    b.HasData(
                        new
                        {
                            RolesUserId = 1,
                            RolId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "System",
                            LastName = "",
                            Password = "System",
                            Username = "System",
                            isActive = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Compras.ComprasDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("CostoUnitario")
                        .HasColumnType("int");

                    b.Property<int>("EncabezadoId")
                        .HasColumnType("int");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EncabezadoId");

                    b.HasIndex("MediaId");

                    b.ToTable("ComprasDetalle");
                });

            modelBuilder.Entity("Domain.Entities.Compras.ComprasEnc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorUser")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<bool>("Pagado")
                        .HasColumnType("bit");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("ComprasEnc");
                });

            modelBuilder.Entity("Domain.Entities.Compras.MedioPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedioPago");
                });

            modelBuilder.Entity("Domain.Entities.Compras.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.EstadosFactu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadosFactu");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.FacturaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("EncabezadoId")
                        .HasColumnType("int");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.Property<int>("PrecioUnitario")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EncabezadoId");

                    b.HasIndex("MediaId");

                    b.ToTable("FacturaDetalle");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.FacturaEnc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<int>("CreadoPorUser")
                        .HasColumnType("int");

                    b.Property<int>("EstadoFactuId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedioPagoId")
                        .HasColumnType("int");

                    b.Property<string>("NoGuia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoEnvioId")
                        .HasColumnType("int");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.Property<int?>("TransportadoraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("EstadoFactuId");

                    b.HasIndex("MedioPagoId");

                    b.HasIndex("TipoEnvioId");

                    b.HasIndex("TransportadoraId");

                    b.ToTable("FacturaEnc");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.TipoEnvios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoEnvios");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.Transportadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CostoEnvio")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProcentajeVenta")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transportadora");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bodegas");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RgbColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blanco",
                            RgbColor = "#ffffff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Negro",
                            RgbColor = "#000000"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rojo",
                            RgbColor = "#FF0000"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beige",
                            RgbColor = "#F3E5AB"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fucsia",
                            RgbColor = "#E68FAC"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Azul",
                            RgbColor = "#0000ff"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Amarillo",
                            RgbColor = "#FFFF00"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Verde",
                            RgbColor = "#008000"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Diseno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Disenos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Estampado"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jaspeado - Chispas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jaspeado - Cuadros"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Anti Resvalante"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Patas Pollo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Importadas"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gala - Económicas"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gala - Importadas"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Edu. Física - Económicas"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Edu. Física - Importadas"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Existencias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadProducto")
                        .HasColumnType("int");

                    b.Property<int>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.ToTable("Existencias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adiddas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 4,
                            Name = "XPN"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jogo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "alo"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodegaId")
                        .HasColumnType("int");

                    b.Property<int?>("DisenoId")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SegmentoId")
                        .HasColumnType("int");

                    b.Property<int?>("TamanoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoMediaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.HasIndex("DisenoId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("SegmentoId");

                    b.HasIndex("TamanoId");

                    b.HasIndex("TipoMediaId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.MediaColores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MediaId");

                    b.ToTable("MediaColores");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Segmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Segmentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adultos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Niños"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Tamano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tamanos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Larga"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tobillera"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Canilleras"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tobilleras largas (2/4)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Talonera"
                        },
                        new
                        {
                            Id = 6,
                            Name = "3/4"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pantalon"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pernera"
                        },
                        new
                        {
                            Id = 9,
                            Name = "6-8"
                        },
                        new
                        {
                            Id = 10,
                            Name = "4-6"
                        },
                        new
                        {
                            Id = 11,
                            Name = "8-10"
                        },
                        new
                        {
                            Id = 12,
                            Name = "9-11"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.TipoMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Deportivas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Calcetines"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mallas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bucaneras"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Calentadora"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Compresoras"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dercoradas"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Colegialas"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antideslizante"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.RolesUser", b =>
                {
                    b.HasOne("Domain.Entities.Authorization.Rol", "Rol")
                        .WithOne("RolesUser")
                        .HasForeignKey("Domain.Entities.Authorization.RolesUser", "RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authorization.User", "User")
                        .WithOne("RolesUser")
                        .HasForeignKey("Domain.Entities.Authorization.RolesUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Compras.ComprasDetalle", b =>
                {
                    b.HasOne("Domain.Entities.Compras.ComprasEnc", "Encabezado")
                        .WithMany("ComprasDetalle")
                        .HasForeignKey("EncabezadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Inventario.Media", "Media")
                        .WithMany("ComprasDetalle")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encabezado");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.Compras.ComprasEnc", b =>
                {
                    b.HasOne("Domain.Entities.Compras.MedioPago", "MedioPago")
                        .WithMany("ComprasEnc")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Compras.Proveedor", "Proveedor")
                        .WithMany("ComprasEnc")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MedioPago");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.FacturaDetalle", b =>
                {
                    b.HasOne("Domain.Entities.Facturacion.FacturaEnc", "Encabezado")
                        .WithMany("FacturaDetalle")
                        .HasForeignKey("EncabezadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Inventario.Media", "Media")
                        .WithMany("FacturaDetalle")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Encabezado");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.FacturaEnc", b =>
                {
                    b.HasOne("Domain.Entities.Facturacion.Clientes", "Cliente")
                        .WithMany("FacturaEnc")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Facturacion.EstadosFactu", "EstadoFactu")
                        .WithMany("FacturaEnc")
                        .HasForeignKey("EstadoFactuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Compras.MedioPago", "MedioPago")
                        .WithMany("FacturaEnc")
                        .HasForeignKey("MedioPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Facturacion.TipoEnvios", "TipoEnvio")
                        .WithMany("FacturaEnc")
                        .HasForeignKey("TipoEnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Facturacion.Transportadora", "Transportadora")
                        .WithMany("FacturaEnc")
                        .HasForeignKey("TransportadoraId");

                    b.Navigation("Cliente");

                    b.Navigation("EstadoFactu");

                    b.Navigation("MedioPago");

                    b.Navigation("TipoEnvio");

                    b.Navigation("Transportadora");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Existencias", b =>
                {
                    b.HasOne("Domain.Entities.Inventario.Media", "Media")
                        .WithMany("Existencias")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Media", b =>
                {
                    b.HasOne("Domain.Entities.Inventario.Bodega", "Bodega")
                        .WithMany("Medias")
                        .HasForeignKey("BodegaId");

                    b.HasOne("Domain.Entities.Inventario.Diseno", "Diseno")
                        .WithMany("Medias")
                        .HasForeignKey("DisenoId");

                    b.HasOne("Domain.Entities.Inventario.Marca", "Marca")
                        .WithMany("Medias")
                        .HasForeignKey("MarcaId");

                    b.HasOne("Domain.Entities.Inventario.Segmento", "Segmento")
                        .WithMany("Medias")
                        .HasForeignKey("SegmentoId");

                    b.HasOne("Domain.Entities.Inventario.Tamano", "Tamano")
                        .WithMany("Medias")
                        .HasForeignKey("TamanoId");

                    b.HasOne("Domain.Entities.Inventario.TipoMedia", "TipoMedia")
                        .WithMany("Medias")
                        .HasForeignKey("TipoMediaId");

                    b.Navigation("Bodega");

                    b.Navigation("Diseno");

                    b.Navigation("Marca");

                    b.Navigation("Segmento");

                    b.Navigation("Tamano");

                    b.Navigation("TipoMedia");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.MediaColores", b =>
                {
                    b.HasOne("Domain.Entities.Inventario.Color", "Color")
                        .WithMany("MediaColores")
                        .HasForeignKey("ColorId");

                    b.HasOne("Domain.Entities.Inventario.Media", "Media")
                        .WithMany("MediaColores")
                        .HasForeignKey("MediaId");

                    b.Navigation("Color");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.Rol", b =>
                {
                    b.Navigation("RolesUser");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.User", b =>
                {
                    b.Navigation("RolesUser");
                });

            modelBuilder.Entity("Domain.Entities.Compras.ComprasEnc", b =>
                {
                    b.Navigation("ComprasDetalle");
                });

            modelBuilder.Entity("Domain.Entities.Compras.MedioPago", b =>
                {
                    b.Navigation("ComprasEnc");

                    b.Navigation("FacturaEnc");
                });

            modelBuilder.Entity("Domain.Entities.Compras.Proveedor", b =>
                {
                    b.Navigation("ComprasEnc");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.Clientes", b =>
                {
                    b.Navigation("FacturaEnc");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.EstadosFactu", b =>
                {
                    b.Navigation("FacturaEnc");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.FacturaEnc", b =>
                {
                    b.Navigation("FacturaDetalle");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.TipoEnvios", b =>
                {
                    b.Navigation("FacturaEnc");
                });

            modelBuilder.Entity("Domain.Entities.Facturacion.Transportadora", b =>
                {
                    b.Navigation("FacturaEnc");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Bodega", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Color", b =>
                {
                    b.Navigation("MediaColores");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Diseno", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Marca", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Media", b =>
                {
                    b.Navigation("ComprasDetalle");

                    b.Navigation("Existencias");

                    b.Navigation("FacturaDetalle");

                    b.Navigation("MediaColores");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Segmento", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Tamano", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.TipoMedia", b =>
                {
                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
