// <auto-generated />
using System;
using Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Domain.Migrations
{
    [DbContext(typeof(GestionDbContext))]
    [Migration("20240323231854_mediaColores")]
    partial class mediaColores
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Authorization.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.RolesUser", b =>
                {
                    b.Property<int>("RolesUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolesUserId"));

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RolesUserId");

                    b.HasIndex("RolId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RolesUser");

                    b.HasData(
                        new
                        {
                            RolesUserId = 1,
                            RolId = 1,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "System",
                            LastName = "",
                            Password = "System",
                            Username = "System",
                            isActive = false
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Bodegas");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RgbColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Colores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Blanco",
                            RgbColor = "#ffffff"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Negro",
                            RgbColor = "#ffffff"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rojo",
                            RgbColor = "#ffffff"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beige/Negro",
                            RgbColor = "#ffffff"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Diseno", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Disenos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Estampado"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jaspeado - Chispas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jaspeado - Cuadros"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Anti Resvalante"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Patas Pollo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Importadas"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Gala - Económicas"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Gala - Importadas"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Edu. Física - Económicas"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Edu. Física - Importadas"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Marcas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adiddas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 4,
                            Name = "XPN"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jogo"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 7,
                            Name = "alo"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BodegaId")
                        .HasColumnType("int");

                    b.Property<int?>("DisenoId")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProveedorId")
                        .HasColumnType("int");

                    b.Property<int?>("SegmentoId")
                        .HasColumnType("int");

                    b.Property<int?>("TamanoId")
                        .HasColumnType("int");

                    b.Property<int?>("TipoMediaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BodegaId");

                    b.HasIndex("DisenoId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("SegmentoId");

                    b.HasIndex("TamanoId");

                    b.HasIndex("TipoMediaId");

                    b.ToTable("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.MediaColores", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("MediaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MediaId");

                    b.ToTable("MediaColores");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Segmento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Segmentos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adultos"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Niños"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Tamano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tamanos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Larga"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tobillera"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Canilleras"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tobilleras largas (2/4)"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Talonera"
                        },
                        new
                        {
                            Id = 6,
                            Name = "3/4"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pantalon"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Pernera"
                        },
                        new
                        {
                            Id = 9,
                            Name = "6-8"
                        },
                        new
                        {
                            Id = 10,
                            Name = "4-6"
                        },
                        new
                        {
                            Id = 11,
                            Name = "8-10"
                        },
                        new
                        {
                            Id = 12,
                            Name = "9-11"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Inventario.TipoMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoMedias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Deportivas"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Calcetines"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mallas"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bucaneras"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Calentadora"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Compresoras"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dercoradas"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Colegialas"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Antideslizante"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Authorization.RolesUser", b =>
                {
                    b.HasOne("Domain.Entities.Authorization.Rol", "Rol")
                        .WithOne("RolesUser")
                        .HasForeignKey("Domain.Entities.Authorization.RolesUser", "RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Authorization.User", "User")
                        .WithOne("RolesUser")
                        .HasForeignKey("Domain.Entities.Authorization.RolesUser", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Media", b =>
                {
                    b.HasOne("Domain.Entities.Inventario.Bodega", "Bodega")
                        .WithMany("Medias")
                        .HasForeignKey("BodegaId");

                    b.HasOne("Domain.Entities.Inventario.Diseno", "Diseno")
                        .WithMany("Medias")
                        .HasForeignKey("DisenoId");

                    b.HasOne("Domain.Entities.Inventario.Marca", "Marca")
                        .WithMany("Medias")
                        .HasForeignKey("MarcaId");

                    b.HasOne("Domain.Entities.Inventario.Proveedor", "Proveedor")
                        .WithMany("Medias")
                        .HasForeignKey("ProveedorId");

                    b.HasOne("Domain.Entities.Inventario.Segmento", "Segmento")
                        .WithMany("Medias")
                        .HasForeignKey("SegmentoId");

                    b.HasOne("Domain.Entities.Inventario.Tamano", "Tamano")
                        .WithMany("Medias")
                        .HasForeignKey("TamanoId");

                    b.HasOne("Domain.Entities.Inventario.TipoMedia", "TipoMedia")
                        .WithMany("Medias")
                        .HasForeignKey("TipoMediaId");

                    b.Navigation("Bodega");

                    b.Navigation("Diseno");

                    b.Navigation("Marca");

                    b.Navigation("Proveedor");

                    b.Navigation("Segmento");

                    b.Navigation("Tamano");

                    b.Navigation("TipoMedia");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.MediaColores", b =>
                {
                    b.HasOne("Domain.Entities.Inventario.Color", "Color")
                        .WithMany("MediaColores")
                        .HasForeignKey("ColorId");

                    b.HasOne("Domain.Entities.Inventario.Media", "Media")
                        .WithMany("MediaColores")
                        .HasForeignKey("MediaId");

                    b.Navigation("Color");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.Rol", b =>
                {
                    b.Navigation("RolesUser");
                });

            modelBuilder.Entity("Domain.Entities.Authorization.User", b =>
                {
                    b.Navigation("RolesUser");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Bodega", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Color", b =>
                {
                    b.Navigation("MediaColores");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Diseno", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Marca", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Media", b =>
                {
                    b.Navigation("MediaColores");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Proveedor", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Segmento", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.Tamano", b =>
                {
                    b.Navigation("Medias");
                });

            modelBuilder.Entity("Domain.Entities.Inventario.TipoMedia", b =>
                {
                    b.Navigation("Medias");
                });
#pragma warning restore 612, 618
        }
    }
}
